version: 2
jobs:
    build:
        docker:
            - image: theorangeone/docker-pandoc
        steps:
            - checkout
            - run: apk add --update --no-cache texmf-dist-fontsextra
            - run: cd authorized-to-keep-kit/ && ./make.sh ABC
            - run: make -C overnight-battery-loan
            - store_artifacts:
                path: authorized-to-keep-kit/ABC.pdf
            - store_artifacts:
                path: overnight-battery-loan/form.pdf
